sonar.projectKey=yogiaprioravelware_template-backend-yogi2
sonar.organization=yogiaprioravelware
sonar.projectName=Template Backend
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sources=src
sonar.cpd.exclusions=src/migrations/**,src/seeders/**
sonar.coverage.exclusions=src/migrations/**,src/seeders/**
